name = "book-catalog"
type = "javascript"
main = "index.js"
account_id = "d6a1f43dd0b2d4efd5e301baa532fe30"  # Replace with your account ID
workers_dev = false
route = "https://www.mayous.org/book-catalog*"
